# Generated by Django 4.1.3 on 2022-11-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('model_name', models.CharField(max_length=200)),
                ('brand_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('condition', models.CharField(choices=[('N', 'New'), ('LN', 'Like-New'), ('U', 'Used')], max_length=2)),
            ],
        ),
    ]
