# Generated by Django 4.1.3 on 2022-11-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlyBikesApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikemodel',
            name='location_rescued',
        ),
        migrations.AddField(
            model_name='bikemodel',
            name='image',
            field=models.ImageField(default=1, upload_to='upload/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bikemodel',
            name='rescued_lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bikemodel',
            name='rescued_long',
            field=models.FloatField(default=0),
        ),
    ]
