# Generated by Django 4.1.3 on 2022-11-05 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlyBikesApp', '0002_bikemodel_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bikemodel',
            old_name='brand_name',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='bikemodel',
            old_name='model_name',
            new_name='model',
        ),
    ]
