# Generated by Django 4.1.3 on 2022-11-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlyBikesApp', '0006_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='endRental',
            field=models.DateTimeField(default='2002-06-05'),
        ),
        migrations.AlterField(
            model_name='user',
            name='startRental',
            field=models.DateTimeField(default='2002-06-05'),
        ),
    ]
