# Generated by Django 4.1.3 on 2022-11-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlyBikesApp', '0007_user_phone_number_alter_user_endrental_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikemodel',
            name='image',
            field=models.ImageField(default=1, upload_to='bikes'),
            preserve_default=False,
        ),
    ]
