# Generated by Django 4.1.3 on 2022-11-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlyBikesApp', '0008_bikemodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='endRental',
        ),
        migrations.RemoveField(
            model_name='user',
            name='startRental',
        ),
        migrations.AddField(
            model_name='bikemodel',
            name='endRental',
            field=models.DateTimeField(default='2002-06-05'),
        ),
        migrations.AddField(
            model_name='bikemodel',
            name='startRental',
            field=models.DateTimeField(default='2002-06-05'),
        ),
        migrations.AlterField(
            model_name='bikemodel',
            name='image',
            field=models.ImageField(upload_to='onlyBikesApp/bikes'),
        ),
    ]
