# Generated by Django 4.1.3 on 2022-11-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlyBikesApp', '0009_remove_user_endrental_remove_user_startrental_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikemodel',
            name='beingRented',
            field=models.BooleanField(default=False),
        ),
    ]
