# Generated by Django 4.1.3 on 2022-11-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlyBikesApp', '0010_bikemodel_beingrented'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bike_model',
            new_name='bikes',
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default=1, upload_to='onlyBikesApp/userprofile'),
            preserve_default=False,
        ),
    ]
