# Generated by Django 3.2.5 on 2022-11-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlyBikesApp', '0012_alter_user_bikes_alter_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikemodel',
            name='image',
        ),
        migrations.AddField(
            model_name='bikemodel',
            name='image_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='/default.png', upload_to=''),
        ),
    ]
