# Generated by Django 3.2.5 on 2022-11-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlyBikesApp', '0013_auto_20221105_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikemodel',
            name='original_owner',
            field=models.CharField(default='', max_length=200),
        ),
    ]
