# Generated by Django 3.2.5 on 2022-11-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlyBikesApp', '0015_auto_20221106_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikemodel',
            name='location_rescued',
        ),
        migrations.AddField(
            model_name='bikemodel',
            name='rescued_lat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bikemodel',
            name='rescued_long',
            field=models.IntegerField(default=0),
        ),
    ]
