# Generated by Django 3.2.5 on 2022-11-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlyBikesApp', '0016_auto_20221106_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikemodel',
            name='rescued_lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bikemodel',
            name='rescued_long',
            field=models.FloatField(default=0),
        ),
    ]
