# Generated by Django 3.2.5 on 2022-11-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlyBikesApp', '0017_auto_20221106_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikemodel',
            name='rescued_lat',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bikemodel',
            name='rescued_long',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
    ]
