# Generated by Django 4.1.3 on 2022-11-06 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlyBikesApp', '0016_bikemodel_image_dir_alter_bikemodel_brand_and_more'),
        ('onlyBikesApp', '0019_auto_20221106_0323'),
    ]

    operations = [
    ]
