# Generated by Django 4.1.3 on 2022-11-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlyBikesApp', '0020_merge_20221106_0550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikemodel',
            name='rescued_lat',
        ),
        migrations.RemoveField(
            model_name='bikemodel',
            name='rescued_long',
        ),
        migrations.AddField(
            model_name='bikemodel',
            name='location_rescued',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bikemodel',
            name='beingRented',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='bikemodel',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bikemodel',
            name='condition',
            field=models.CharField(blank=True, choices=[('N', 'New'), ('LN', 'Like-New'), ('U', 'Used')], default='U', max_length=2),
        ),
        migrations.AlterField(
            model_name='bikemodel',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='bikemodel',
            name='endRental',
            field=models.DateTimeField(blank=True, default='2002-06-05'),
        ),
        migrations.AlterField(
            model_name='bikemodel',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bikemodel',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bikemodel',
            name='model',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bikemodel',
            name='original_owner',
            field=models.CharField(blank=True, default='rescued', max_length=200),
        ),
        migrations.AlterField(
            model_name='bikemodel',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='bikemodel',
            name='startRental',
            field=models.DateTimeField(blank=True, default='2002-06-05'),
        ),
    ]
